# The format version of this config file
version: 1
# Config shares/schemas/tables to share
shares:
- name: "<share name>"
  schemas:
  - name: "<schema name>"
    tables:
    - name: "<table name>"
     # Azure Data Lake Storage Gen2. See https://github.com/delta-io/delta-sharing#azure-data-lake-storage-gen2 for how to config the credentials
      location: "abfss://<container name>@<storage account name>.dfs.core.windows.net/<table path>"
# Set the host name that the server will use
host: "<docker host IP>"
# Set the port that the server will listen on. Note: using ports below 1024 
# may require a privileged user in some operating systems.
port: 8080
# Set the url prefix for the REST APIs
endpoint: "/delta-sharing"
# Set the timeout of S3 presigned url in seconds
preSignedUrlTimeoutSeconds: 3600
# How many tables to cache in the server
deltaTableCacheSize: 10
# Whether we can accept working with a stale version of the table. This is useful when sharing
# static tables that will never be changed.
stalenessAcceptable: false
# Whether to evaluate user provided `predicateHints`
evaluatePredicateHints: false
# Auth Token is Optional
authorization:
  bearerToken: "<token>"
